function huberh = tak_handle_hinge_huber(d)
% function handle for huber hinge loss function
%  d = huber-hinge parameter: transition point from hinge to hinge-squared
% - fields contains function value, gradient value, and proximal operator%%
%%
huberh.func=@(t) ...          
            (t<=(1-d)).*(1-t-d/2) + ......
            ((1-d)<t).*(t<=1).*(1-t).^2/(2*d);
huberh.grad=@(t) ...
            (t<=(1-d)).*(-1) + ......
            ((1-d)<t).*(t<=1).*(t-1)/d; % derivative
huberh.prox=@(t,tau) ...
            (t<=(1-d-tau)).*(t+tau) + ...
            (t<1).*(t>(1-d-tau)).*(t+tau/d)./(1+tau/d) + ...
            (t>=1).*t; % proximal operator